// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_scrMotion = NULL;lv_obj_t *ui_topBar2 = NULL;lv_obj_t *ui_outerRing = NULL;lv_obj_t *ui_innerRing = NULL;lv_obj_t *ui_dotRing = NULL;lv_obj_t *ui_cntFooter2 = NULL;lv_obj_t *ui_cntActiveStatus2 = NULL;lv_obj_t *ui_iconLeft2 = NULL;lv_obj_t *ui_iconRight2 = NULL;lv_obj_t *ui_activeDot2 = NULL;lv_obj_t *ui_active2 = NULL;lv_obj_t *ui_inactiveDot5 = NULL;lv_obj_t *ui_inactiveDot6 = NULL;lv_obj_t *ui_hline = NULL;lv_obj_t *ui_vline = NULL;lv_obj_t *ui_bubble = NULL;lv_obj_t *ui_cntAxisX = NULL;lv_obj_t *ui_axisX = NULL;lv_obj_t *ui_axisXv = NULL;lv_obj_t *ui_unit1 = NULL;lv_obj_t *ui_cntAxisY = NULL;lv_obj_t *ui_axisY = NULL;lv_obj_t *ui_axisYv = NULL;lv_obj_t *ui_unit2 = NULL;lv_obj_t *ui_cntAxisZ = NULL;lv_obj_t *ui_axisZ = NULL;lv_obj_t *ui_axisZv = NULL;lv_obj_t *ui_unit3 = NULL;
// event funtions

// build funtions

void ui_scrMotion_screen_init(void)
{
ui_scrMotion = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrMotion, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrMotion, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_backGround);
ui_object_set_themeable_style_property(ui_scrMotion, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_backGround);

ui_topBar2 = ui_topBar_create(ui_scrMotion);
lv_obj_set_x( ui_topBar2, 0 );
lv_obj_set_y( ui_topBar2, 0 );

ui_outerRing = lv_arc_create(ui_scrMotion);
lv_obj_set_width( ui_outerRing, 118);
lv_obj_set_height( ui_outerRing, 118);
lv_obj_set_x( ui_outerRing, 18 );
lv_obj_set_y( ui_outerRing, 57 );
lv_arc_set_value(ui_outerRing, 0);
lv_arc_set_bg_angles(ui_outerRing,0,360);
ui_object_set_themeable_style_property(ui_outerRing, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_outerRing, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_border);
lv_obj_set_style_arc_width(ui_outerRing, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_outerRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_outerRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_outerRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_outerRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_innerRing = lv_arc_create(ui_scrMotion);
lv_obj_set_width( ui_innerRing, 74);
lv_obj_set_height( ui_innerRing, 74);
lv_obj_set_x( ui_innerRing, 40 );
lv_obj_set_y( ui_innerRing, 78 );
lv_arc_set_value(ui_innerRing, 0);
lv_arc_set_bg_angles(ui_innerRing,0,360);
ui_object_set_themeable_style_property(ui_innerRing, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_divider);
ui_object_set_themeable_style_property(ui_innerRing, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_divider);
lv_obj_set_style_arc_width(ui_innerRing, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_innerRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_innerRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_innerRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_innerRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_dotRing = lv_arc_create(ui_scrMotion);
lv_obj_set_width( ui_dotRing, 26);
lv_obj_set_height( ui_dotRing, 26);
lv_obj_set_x( ui_dotRing, 64 );
lv_obj_set_y( ui_dotRing, 103 );
lv_arc_set_value(ui_dotRing, 0);
lv_arc_set_bg_angles(ui_dotRing,0,360);
ui_object_set_themeable_style_property(ui_dotRing, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_textTertiary);
ui_object_set_themeable_style_property(ui_dotRing, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_textTertiary);
lv_obj_set_style_arc_width(ui_dotRing, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_dotRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_dotRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_dotRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_dotRing, -10, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_cntFooter2 = lv_obj_create(ui_scrMotion);
lv_obj_remove_style_all(ui_cntFooter2);
lv_obj_set_width( ui_cntFooter2, 320);
lv_obj_set_height( ui_cntFooter2, 26);
lv_obj_set_align( ui_cntFooter2, LV_ALIGN_BOTTOM_LEFT );
lv_obj_remove_flag( ui_cntFooter2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_cntFooter2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_cntFooter2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_cntFooter2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_cntFooter2, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cntActiveStatus2 = lv_obj_create(ui_cntFooter2);
lv_obj_remove_style_all(ui_cntActiveStatus2);
lv_obj_set_width( ui_cntActiveStatus2, 100);
lv_obj_set_height( ui_cntActiveStatus2, 26);
lv_obj_set_align( ui_cntActiveStatus2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_cntActiveStatus2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_iconLeft2 = lv_image_create(ui_cntFooter2);
lv_image_set_src(ui_iconLeft2, &ui_img_icons_left_png);
lv_obj_set_width( ui_iconLeft2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_iconLeft2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_iconLeft2, 10 );
lv_obj_set_y( ui_iconLeft2, 0 );
lv_obj_set_align( ui_iconLeft2, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_iconLeft2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_iconLeft2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_iconLeft2,175);
ui_object_set_themeable_style_property(ui_iconLeft2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_textTertiary);
ui_object_set_themeable_style_property(ui_iconLeft2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_textTertiary);

ui_iconRight2 = lv_image_create(ui_cntFooter2);
lv_image_set_src(ui_iconRight2, &ui_img_icons_right_png);
lv_obj_set_width( ui_iconRight2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_iconRight2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_iconRight2, -10 );
lv_obj_set_y( ui_iconRight2, 0 );
lv_obj_set_align( ui_iconRight2, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_iconRight2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_iconRight2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_iconRight2,175);
ui_object_set_themeable_style_property(ui_iconRight2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_textTertiary);
ui_object_set_themeable_style_property(ui_iconRight2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_textTertiary);

ui_activeDot2 = lv_arc_create(ui_cntFooter2);
lv_obj_set_width( ui_activeDot2, 8);
lv_obj_set_height( ui_activeDot2, 8);
lv_obj_set_x( ui_activeDot2, 105 );
lv_obj_set_y( ui_activeDot2, 0 );
lv_obj_set_align( ui_activeDot2, LV_ALIGN_LEFT_MID );
lv_arc_set_value(ui_activeDot2, 100);
lv_arc_set_bg_angles(ui_activeDot2,0,360);

ui_object_set_themeable_style_property(ui_activeDot2, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_activeDot2, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_accent);

lv_obj_set_style_pad_left(ui_activeDot2, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_activeDot2, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_activeDot2, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_activeDot2, -40, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_active2 = lv_label_create(ui_cntFooter2);
lv_obj_set_width( ui_active2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_active2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_active2, 10 );
lv_obj_set_y( ui_active2, 0 );
lv_obj_set_align( ui_active2, LV_ALIGN_CENTER );
lv_label_set_text(ui_active2,"MOTION");
ui_object_set_themeable_style_property(ui_active2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_active2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_accent);
lv_obj_set_style_text_letter_space(ui_active2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_active2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_active2, &ui_font_micro8b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_inactiveDot5 = lv_arc_create(ui_cntFooter2);
lv_obj_set_width( ui_inactiveDot5, 8);
lv_obj_set_height( ui_inactiveDot5, 8);
lv_obj_set_x( ui_inactiveDot5, 120 );
lv_obj_set_y( ui_inactiveDot5, 0 );
lv_obj_set_align( ui_inactiveDot5, LV_ALIGN_LEFT_MID );
lv_arc_set_value(ui_inactiveDot5, 100);
lv_arc_set_bg_angles(ui_inactiveDot5,0,360);

ui_object_set_themeable_style_property(ui_inactiveDot5, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_textTertiary);
ui_object_set_themeable_style_property(ui_inactiveDot5, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_textTertiary);

lv_obj_set_style_pad_left(ui_inactiveDot5, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_inactiveDot5, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_inactiveDot5, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_inactiveDot5, -40, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_inactiveDot6 = lv_arc_create(ui_cntFooter2);
lv_obj_set_width( ui_inactiveDot6, 8);
lv_obj_set_height( ui_inactiveDot6, 8);
lv_obj_set_x( ui_inactiveDot6, 135 );
lv_obj_set_y( ui_inactiveDot6, 0 );
lv_obj_set_align( ui_inactiveDot6, LV_ALIGN_LEFT_MID );
lv_arc_set_value(ui_inactiveDot6, 100);
lv_arc_set_bg_angles(ui_inactiveDot6,0,360);

ui_object_set_themeable_style_property(ui_inactiveDot6, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_textTertiary);
ui_object_set_themeable_style_property(ui_inactiveDot6, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_textTertiary);

lv_obj_set_style_pad_left(ui_inactiveDot6, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_inactiveDot6, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_inactiveDot6, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_inactiveDot6, -40, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_hline = lv_obj_create(ui_scrMotion);
lv_obj_remove_style_all(ui_hline);
lv_obj_set_width( ui_hline, 118);
lv_obj_set_height( ui_hline, 1);
lv_obj_set_x( ui_hline, 18 );
lv_obj_set_y( ui_hline, 116 );
lv_obj_remove_flag( ui_hline, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_hline, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_hline, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_hline, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_hline, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_vline = lv_obj_create(ui_scrMotion);
lv_obj_remove_style_all(ui_vline);
lv_obj_set_width( ui_vline, 1);
lv_obj_set_height( ui_vline, 118);
lv_obj_set_x( ui_vline, 77 );
lv_obj_set_y( ui_vline, 57 );
lv_obj_remove_flag( ui_vline, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_vline, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_vline, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_vline, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_vline, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bubble = lv_arc_create(ui_scrMotion);
lv_obj_set_width( ui_bubble, 18);
lv_obj_set_height( ui_bubble, 18);
lv_obj_set_x( ui_bubble, 68 );
lv_obj_set_y( ui_bubble, 107 );
lv_arc_set_value(ui_bubble, 100);
lv_arc_set_bg_angles(ui_bubble,0,360);
lv_obj_set_style_arc_width(ui_bubble, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_bubble, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_statusConnected);
ui_object_set_themeable_style_property(ui_bubble, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_statusConnected);
lv_obj_set_style_arc_width(ui_bubble, 7, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_bubble, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_bubble, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_bubble, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_bubble, -10, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_cntAxisX = lv_obj_create(ui_scrMotion);
lv_obj_remove_style_all(ui_cntAxisX);
lv_obj_set_width( ui_cntAxisX, 156);
lv_obj_set_height( ui_cntAxisX, 28);
lv_obj_set_x( ui_cntAxisX, 152 );
lv_obj_set_y( ui_cntAxisX, 67 );
lv_obj_remove_flag( ui_cntAxisX, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_cntAxisX, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_cntAxisX, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_cntAxisX, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_cntAxisX, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisX = lv_label_create(ui_cntAxisX);
lv_obj_set_width( ui_axisX, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisX, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_axisX, 0 );
lv_obj_set_y( ui_axisX, 7 );
lv_label_set_text(ui_axisX,"X");
ui_object_set_themeable_style_property(ui_axisX, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_axisX, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_accent);
lv_obj_set_style_text_font(ui_axisX, &ui_font_caps11b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisXv = lv_label_create(ui_cntAxisX);
lv_obj_set_width( ui_axisXv, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisXv, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_axisXv, 20 );
lv_obj_set_y( ui_axisXv, 2 );
lv_label_set_text(ui_axisXv,"+0.00");
lv_obj_set_style_text_font(ui_axisXv, &ui_font_mono17m, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_unit1 = lv_label_create(ui_cntAxisX);
lv_obj_set_width( ui_unit1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_unit1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_unit1, 149 );
lv_obj_set_y( ui_unit1, 7 );
lv_label_set_text(ui_unit1,"g");
ui_object_set_themeable_style_property(ui_unit1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_unit1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_accent);
lv_obj_set_style_text_font(ui_unit1, &ui_font_caps11b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cntAxisY = lv_obj_create(ui_scrMotion);
lv_obj_remove_style_all(ui_cntAxisY);
lv_obj_set_width( ui_cntAxisY, 156);
lv_obj_set_height( ui_cntAxisY, 28);
lv_obj_set_x( ui_cntAxisY, 152 );
lv_obj_set_y( ui_cntAxisY, 95 );
lv_obj_remove_flag( ui_cntAxisY, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_cntAxisY, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_cntAxisY, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_cntAxisY, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_cntAxisY, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisY = lv_label_create(ui_cntAxisY);
lv_obj_set_width( ui_axisY, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisY, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_axisY, 0 );
lv_obj_set_y( ui_axisY, 7 );
lv_label_set_text(ui_axisY,"Y");
ui_object_set_themeable_style_property(ui_axisY, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_axisY, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_accent);
lv_obj_set_style_text_font(ui_axisY, &ui_font_caps11b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisYv = lv_label_create(ui_cntAxisY);
lv_obj_set_width( ui_axisYv, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisYv, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_axisYv, 20 );
lv_obj_set_y( ui_axisYv, 2 );
lv_label_set_text(ui_axisYv,"+0.00");
lv_obj_set_style_text_font(ui_axisYv, &ui_font_mono17m, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_unit2 = lv_label_create(ui_cntAxisY);
lv_obj_set_width( ui_unit2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_unit2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_unit2, 149 );
lv_obj_set_y( ui_unit2, 7 );
lv_label_set_text(ui_unit2,"g");
ui_object_set_themeable_style_property(ui_unit2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_unit2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_accent);
lv_obj_set_style_text_font(ui_unit2, &ui_font_caps11b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cntAxisZ = lv_obj_create(ui_scrMotion);
lv_obj_remove_style_all(ui_cntAxisZ);
lv_obj_set_width( ui_cntAxisZ, 156);
lv_obj_set_height( ui_cntAxisZ, 28);
lv_obj_set_x( ui_cntAxisZ, 152 );
lv_obj_set_y( ui_cntAxisZ, 123 );
lv_obj_remove_flag( ui_cntAxisZ, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_cntAxisZ, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_cntAxisZ, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_cntAxisZ, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_cntAxisZ, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisZ = lv_label_create(ui_cntAxisZ);
lv_obj_set_width( ui_axisZ, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisZ, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_axisZ, 0 );
lv_obj_set_y( ui_axisZ, 7 );
lv_label_set_text(ui_axisZ,"Z");
ui_object_set_themeable_style_property(ui_axisZ, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_axisZ, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_accent);
lv_obj_set_style_text_font(ui_axisZ, &ui_font_caps11b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisZv = lv_label_create(ui_cntAxisZ);
lv_obj_set_width( ui_axisZv, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisZv, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_axisZv, 20 );
lv_obj_set_y( ui_axisZv, 2 );
lv_label_set_text(ui_axisZv,"+0.00");
lv_obj_set_style_text_font(ui_axisZv, &ui_font_mono17m, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_unit3 = lv_label_create(ui_cntAxisZ);
lv_obj_set_width( ui_unit3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_unit3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_unit3, 149 );
lv_obj_set_y( ui_unit3, 7 );
lv_label_set_text(ui_unit3,"g");
ui_object_set_themeable_style_property(ui_unit3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_unit3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_accent);
lv_obj_set_style_text_font(ui_unit3, &ui_font_caps11b, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_scrMotion_screen_destroy(void)
{
   if (ui_scrMotion) lv_obj_del(ui_scrMotion);

// NULL screen variables
ui_scrMotion= NULL;
ui_topBar2= NULL;
ui_outerRing= NULL;
ui_innerRing= NULL;
ui_dotRing= NULL;
ui_cntFooter2= NULL;
ui_cntActiveStatus2= NULL;
ui_iconLeft2= NULL;
ui_iconRight2= NULL;
ui_activeDot2= NULL;
ui_active2= NULL;
ui_inactiveDot5= NULL;
ui_inactiveDot6= NULL;
ui_hline= NULL;
ui_vline= NULL;
ui_bubble= NULL;
ui_cntAxisX= NULL;
ui_axisX= NULL;
ui_axisXv= NULL;
ui_unit1= NULL;
ui_cntAxisY= NULL;
ui_axisY= NULL;
ui_axisYv= NULL;
ui_unit2= NULL;
ui_cntAxisZ= NULL;
ui_axisZ= NULL;
ui_axisZv= NULL;
ui_unit3= NULL;

}
