// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCRBLE_H
#define UI_SCRBLE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrBLE
extern void ui_scrBLE_screen_init(void);
extern void ui_scrBLE_screen_destroy(void);
extern lv_obj_t *ui_scrBLE;
extern lv_obj_t *ui_cntStatus;
extern lv_obj_t *ui_lblStatus;
extern lv_obj_t *ui_lblStatusV;
extern lv_obj_t *ui_contTemp;
extern lv_obj_t *ui_imgTemp;
extern lv_obj_t *ui_lblTemp;
extern lv_obj_t *ui_lblTempV;
extern lv_obj_t *ui_contHumidity;
extern lv_obj_t *ui_imgHum;
extern lv_obj_t *ui_lblHum;
extern lv_obj_t *ui_lblHumV;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

