// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_scrBLE = NULL;lv_obj_t *ui_cntStatus = NULL;lv_obj_t *ui_lblStatus = NULL;lv_obj_t *ui_lblStatusV = NULL;lv_obj_t *ui_contTemp = NULL;lv_obj_t *ui_imgTemp = NULL;lv_obj_t *ui_lblTemp = NULL;lv_obj_t *ui_lblTempV = NULL;lv_obj_t *ui_contHumidity = NULL;lv_obj_t *ui_imgHum = NULL;lv_obj_t *ui_lblHum = NULL;lv_obj_t *ui_lblHumV = NULL;
// event funtions

// build funtions

void ui_scrBLE_screen_init(void)
{
ui_scrBLE = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrBLE, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_scrBLE, &ui_img_bg_main_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_cntStatus = lv_obj_create(ui_scrBLE);
lv_obj_remove_style_all(ui_cntStatus);
lv_obj_set_width( ui_cntStatus, 250);
lv_obj_set_height( ui_cntStatus, 30);
lv_obj_set_x( ui_cntStatus, 0 );
lv_obj_set_y( ui_cntStatus, -90 );
lv_obj_set_align( ui_cntStatus, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_cntStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblStatus = lv_label_create(ui_cntStatus);
lv_obj_set_width( ui_lblStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblStatus, 10 );
lv_obj_set_y( ui_lblStatus, 0 );
lv_obj_set_align( ui_lblStatus, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_lblStatus,"Status:");
lv_obj_set_style_text_font(ui_lblStatus, &ui_font_Nunito28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblStatusV = lv_label_create(ui_cntStatus);
lv_obj_set_width( ui_lblStatusV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblStatusV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblStatusV, -10 );
lv_obj_set_y( ui_lblStatusV, 0 );
lv_obj_set_align( ui_lblStatusV, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_lblStatusV,"Advertising");
lv_obj_set_style_text_color(ui_lblStatusV, lv_color_hex(0x4DC748), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblStatusV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblStatusV, &ui_font_Nunito28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_contTemp = lv_obj_create(ui_scrBLE);
lv_obj_remove_style_all(ui_contTemp);
lv_obj_set_width( ui_contTemp, 200);
lv_obj_set_height( ui_contTemp, 64);
lv_obj_set_x( ui_contTemp, 0 );
lv_obj_set_y( ui_contTemp, 75 );
lv_obj_set_align( ui_contTemp, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_contTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgTemp = lv_image_create(ui_contTemp);
lv_image_set_src(ui_imgTemp, &ui_img_icon_temperature_png);
lv_obj_set_width( ui_imgTemp, 64);
lv_obj_set_height( ui_imgTemp, 64);
lv_obj_add_flag( ui_imgTemp, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_imgTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblTemp = lv_label_create(ui_contTemp);
lv_obj_set_width( ui_lblTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTemp, 25 );
lv_obj_set_y( ui_lblTemp, -20 );
lv_obj_set_align( ui_lblTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTemp,"Temperature:");
lv_obj_set_style_text_font(ui_lblTemp, &ui_font_Nunito20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTempV = lv_label_create(ui_contTemp);
lv_obj_set_width( ui_lblTempV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTempV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTempV, 25 );
lv_obj_set_y( ui_lblTempV, 10 );
lv_obj_set_align( ui_lblTempV, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTempV,"00.00 C");
lv_obj_set_style_text_font(ui_lblTempV, &ui_font_Nunito20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_contHumidity = lv_obj_create(ui_scrBLE);
lv_obj_remove_style_all(ui_contHumidity);
lv_obj_set_width( ui_contHumidity, 200);
lv_obj_set_height( ui_contHumidity, 64);
lv_obj_set_x( ui_contHumidity, 0 );
lv_obj_set_y( ui_contHumidity, 150 );
lv_obj_set_align( ui_contHumidity, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_contHumidity, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgHum = lv_image_create(ui_contHumidity);
lv_image_set_src(ui_imgHum, &ui_img_icon_humidity_png);
lv_obj_set_width( ui_imgHum, 64);
lv_obj_set_height( ui_imgHum, 64);
lv_obj_add_flag( ui_imgHum, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_imgHum, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblHum = lv_label_create(ui_contHumidity);
lv_obj_set_width( ui_lblHum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblHum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblHum, 25 );
lv_obj_set_y( ui_lblHum, -20 );
lv_obj_set_align( ui_lblHum, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblHum,"Humidity:");
lv_obj_set_style_text_font(ui_lblHum, &ui_font_Nunito20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblHumV = lv_label_create(ui_contHumidity);
lv_obj_set_width( ui_lblHumV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblHumV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblHumV, 25 );
lv_obj_set_y( ui_lblHumV, 10 );
lv_obj_set_align( ui_lblHumV, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblHumV,"00.00 %");
lv_obj_set_style_text_font(ui_lblHumV, &ui_font_Nunito20, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_scrBLE_screen_destroy(void)
{
   if (ui_scrBLE) lv_obj_del(ui_scrBLE);

// NULL screen variables
ui_scrBLE= NULL;
ui_cntStatus= NULL;
ui_lblStatus= NULL;
ui_lblStatusV= NULL;
ui_contTemp= NULL;
ui_imgTemp= NULL;
ui_lblTemp= NULL;
ui_lblTempV= NULL;
ui_contHumidity= NULL;
ui_imgHum= NULL;
ui_lblHum= NULL;
ui_lblHumV= NULL;

}
