// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCRCLIMATE_H
#define UI_SCRCLIMATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrClimate
extern void ui_scrClimate_screen_init(void);
extern void ui_scrClimate_screen_destroy(void);
extern lv_obj_t *ui_scrClimate;
extern lv_obj_t *ui_topBar1;
extern lv_obj_t *ui_cntTemperature;
extern lv_obj_t *ui_tempArc;
extern lv_obj_t *ui_tempValue;
extern lv_obj_t *ui_tempUnit;
extern lv_obj_t *ui_tempLabel;
extern lv_obj_t *ui_tempMinMax;
extern lv_obj_t *ui_cntHumidity;
extern lv_obj_t *ui_humArc;
extern lv_obj_t *ui_humValue;
extern lv_obj_t *ui_humUnit;
extern lv_obj_t *ui_humLabel;
extern lv_obj_t *ui_humMinMax;
extern lv_obj_t *ui_cntFooter1;
extern lv_obj_t *ui_cntActiveStatus1;
extern lv_obj_t *ui_iconLeft1;
extern lv_obj_t *ui_iconRight1;
extern lv_obj_t *ui_activeDot1;
extern lv_obj_t *ui_active1;
extern lv_obj_t *ui_inactiveDot3;
extern lv_obj_t *ui_inactiveDot4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

