// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_scrClimate = NULL;lv_obj_t *ui_topBar1 = NULL;lv_obj_t *ui_cntTemperature = NULL;lv_obj_t *ui_tempArc = NULL;lv_obj_t *ui_tempValue = NULL;lv_obj_t *ui_tempUnit = NULL;lv_obj_t *ui_tempLabel = NULL;lv_obj_t *ui_tempMinMax = NULL;lv_obj_t *ui_cntHumidity = NULL;lv_obj_t *ui_humArc = NULL;lv_obj_t *ui_humValue = NULL;lv_obj_t *ui_humUnit = NULL;lv_obj_t *ui_humLabel = NULL;lv_obj_t *ui_humMinMax = NULL;lv_obj_t *ui_cntFooter1 = NULL;lv_obj_t *ui_cntActiveStatus1 = NULL;lv_obj_t *ui_iconLeft1 = NULL;lv_obj_t *ui_iconRight1 = NULL;lv_obj_t *ui_activeDot1 = NULL;lv_obj_t *ui_active1 = NULL;lv_obj_t *ui_inactiveDot3 = NULL;lv_obj_t *ui_inactiveDot4 = NULL;
// event funtions

// build funtions

void ui_scrClimate_screen_init(void)
{
ui_scrClimate = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrClimate, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrClimate, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_backGround);
ui_object_set_themeable_style_property(ui_scrClimate, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_backGround);

ui_topBar1 = ui_topBar_create(ui_scrClimate);
lv_obj_set_x( ui_topBar1, 0 );
lv_obj_set_y( ui_topBar1, 0 );

ui_cntTemperature = lv_obj_create(ui_scrClimate);
lv_obj_remove_style_all(ui_cntTemperature);
lv_obj_set_width( ui_cntTemperature, 88);
lv_obj_set_height( ui_cntTemperature, 124);
lv_obj_set_x( ui_cntTemperature, 32 );
lv_obj_set_y( ui_cntTemperature, 63 );
lv_obj_remove_flag( ui_cntTemperature, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_tempArc = lv_arc_create(ui_cntTemperature);
lv_obj_set_width( ui_tempArc, 88);
lv_obj_set_height( ui_tempArc, 88);
lv_arc_set_range(ui_tempArc, 5,40);
lv_arc_set_value(ui_tempArc, 10);
lv_arc_set_bg_angles(ui_tempArc,0,360);
lv_arc_set_rotation(ui_tempArc,-90);
lv_obj_set_style_arc_width(ui_tempArc, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_tempArc, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_tempArc, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_accent);
lv_obj_set_style_arc_width(ui_tempArc, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_tempArc, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_tempArc, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_tempArc, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_tempArc, -10, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_tempValue = lv_label_create(ui_tempArc);
lv_obj_set_width( ui_tempValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tempValue, -8 );
lv_obj_set_y( ui_tempValue, 0 );
lv_obj_set_align( ui_tempValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempValue,"22.0");
lv_obj_set_style_text_font(ui_tempValue, &ui_font_value22b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempUnit = lv_label_create(ui_tempArc);
lv_obj_set_width( ui_tempUnit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempUnit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tempUnit, 25 );
lv_obj_set_y( ui_tempUnit, 4 );
lv_obj_set_align( ui_tempUnit, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempUnit,"°C");
ui_object_set_themeable_style_property(ui_tempUnit, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_textSecondary);
ui_object_set_themeable_style_property(ui_tempUnit, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_textSecondary);
lv_obj_set_style_text_font(ui_tempUnit, &ui_font_caps11b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempLabel = lv_label_create(ui_cntTemperature);
lv_obj_set_width( ui_tempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tempLabel, 0 );
lv_obj_set_y( ui_tempLabel, 95 );
lv_obj_set_align( ui_tempLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_tempLabel,"TEMPERATURE");
ui_object_set_themeable_style_property(ui_tempLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_textSecondary);
ui_object_set_themeable_style_property(ui_tempLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_textSecondary);
lv_obj_set_style_text_letter_space(ui_tempLabel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_tempLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tempLabel, &ui_font_sub10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempMinMax = lv_label_create(ui_cntTemperature);
lv_obj_set_width( ui_tempMinMax, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempMinMax, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tempMinMax, 0 );
lv_obj_set_y( ui_tempMinMax, 112 );
lv_obj_set_align( ui_tempMinMax, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_tempMinMax,"5.0°C - 40.0°C");
ui_object_set_themeable_style_property(ui_tempMinMax, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_textSecondary);
ui_object_set_themeable_style_property(ui_tempMinMax, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_textSecondary);
lv_obj_set_style_text_font(ui_tempMinMax, &ui_font_mono9, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cntHumidity = lv_obj_create(ui_scrClimate);
lv_obj_remove_style_all(ui_cntHumidity);
lv_obj_set_width( ui_cntHumidity, 88);
lv_obj_set_height( ui_cntHumidity, 124);
lv_obj_set_x( ui_cntHumidity, 200 );
lv_obj_set_y( ui_cntHumidity, 63 );
lv_obj_remove_flag( ui_cntHumidity, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_humArc = lv_arc_create(ui_cntHumidity);
lv_obj_set_width( ui_humArc, 88);
lv_obj_set_height( ui_humArc, 88);
lv_arc_set_range(ui_humArc, 0,90);
lv_arc_set_value(ui_humArc, 10);
lv_arc_set_bg_angles(ui_humArc,0,360);
lv_arc_set_rotation(ui_humArc,-90);
lv_obj_set_style_arc_width(ui_humArc, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_humArc, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_humArc, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_accent);
lv_obj_set_style_arc_width(ui_humArc, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_humArc, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_humArc, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_humArc, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_humArc, -10, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_humValue = lv_label_create(ui_humArc);
lv_obj_set_width( ui_humValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humValue, -8 );
lv_obj_set_y( ui_humValue, 0 );
lv_obj_set_align( ui_humValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_humValue,"17.0");
lv_obj_set_style_text_font(ui_humValue, &ui_font_value22b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humUnit = lv_label_create(ui_humArc);
lv_obj_set_width( ui_humUnit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humUnit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humUnit, 25 );
lv_obj_set_y( ui_humUnit, 4 );
lv_obj_set_align( ui_humUnit, LV_ALIGN_CENTER );
lv_label_set_text(ui_humUnit,"%");
ui_object_set_themeable_style_property(ui_humUnit, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_textSecondary);
ui_object_set_themeable_style_property(ui_humUnit, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_textSecondary);
lv_obj_set_style_text_font(ui_humUnit, &ui_font_caps11b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humLabel = lv_label_create(ui_cntHumidity);
lv_obj_set_width( ui_humLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humLabel, 0 );
lv_obj_set_y( ui_humLabel, 95 );
lv_obj_set_align( ui_humLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_humLabel,"HUMIDITY");
ui_object_set_themeable_style_property(ui_humLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_textSecondary);
ui_object_set_themeable_style_property(ui_humLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_textSecondary);
lv_obj_set_style_text_letter_space(ui_humLabel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_humLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_humLabel, &ui_font_sub10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humMinMax = lv_label_create(ui_cntHumidity);
lv_obj_set_width( ui_humMinMax, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humMinMax, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humMinMax, 0 );
lv_obj_set_y( ui_humMinMax, 112 );
lv_obj_set_align( ui_humMinMax, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_humMinMax,"0.0 % - 90.0 %");
ui_object_set_themeable_style_property(ui_humMinMax, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_textSecondary);
ui_object_set_themeable_style_property(ui_humMinMax, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_textSecondary);
lv_obj_set_style_text_font(ui_humMinMax, &ui_font_mono9, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cntFooter1 = lv_obj_create(ui_scrClimate);
lv_obj_remove_style_all(ui_cntFooter1);
lv_obj_set_width( ui_cntFooter1, 320);
lv_obj_set_height( ui_cntFooter1, 26);
lv_obj_set_align( ui_cntFooter1, LV_ALIGN_BOTTOM_LEFT );
lv_obj_remove_flag( ui_cntFooter1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_cntFooter1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_cntFooter1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_cntFooter1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_cntFooter1, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cntActiveStatus1 = lv_obj_create(ui_cntFooter1);
lv_obj_remove_style_all(ui_cntActiveStatus1);
lv_obj_set_width( ui_cntActiveStatus1, 100);
lv_obj_set_height( ui_cntActiveStatus1, 26);
lv_obj_set_align( ui_cntActiveStatus1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_cntActiveStatus1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_iconLeft1 = lv_image_create(ui_cntFooter1);
lv_image_set_src(ui_iconLeft1, &ui_img_icons_left_png);
lv_obj_set_width( ui_iconLeft1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_iconLeft1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_iconLeft1, 10 );
lv_obj_set_y( ui_iconLeft1, 0 );
lv_obj_set_align( ui_iconLeft1, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_iconLeft1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_iconLeft1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_iconLeft1,175);
ui_object_set_themeable_style_property(ui_iconLeft1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_textTertiary);
ui_object_set_themeable_style_property(ui_iconLeft1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_textTertiary);

ui_iconRight1 = lv_image_create(ui_cntFooter1);
lv_image_set_src(ui_iconRight1, &ui_img_icons_right_png);
lv_obj_set_width( ui_iconRight1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_iconRight1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_iconRight1, -10 );
lv_obj_set_y( ui_iconRight1, 0 );
lv_obj_set_align( ui_iconRight1, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_iconRight1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_iconRight1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_iconRight1,175);
ui_object_set_themeable_style_property(ui_iconRight1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_textTertiary);
ui_object_set_themeable_style_property(ui_iconRight1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_textTertiary);

ui_activeDot1 = lv_arc_create(ui_cntFooter1);
lv_obj_set_width( ui_activeDot1, 8);
lv_obj_set_height( ui_activeDot1, 8);
lv_obj_set_x( ui_activeDot1, 125 );
lv_obj_set_y( ui_activeDot1, 0 );
lv_obj_set_align( ui_activeDot1, LV_ALIGN_LEFT_MID );
lv_arc_set_value(ui_activeDot1, 100);
lv_arc_set_bg_angles(ui_activeDot1,0,360);

ui_object_set_themeable_style_property(ui_activeDot1, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_activeDot1, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_accent);

lv_obj_set_style_pad_left(ui_activeDot1, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_activeDot1, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_activeDot1, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_activeDot1, -40, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_active1 = lv_label_create(ui_cntFooter1);
lv_obj_set_width( ui_active1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_active1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_active1, LV_ALIGN_CENTER );
lv_label_set_text(ui_active1,"CLIMATE");
ui_object_set_themeable_style_property(ui_active1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_accent);
ui_object_set_themeable_style_property(ui_active1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_accent);
lv_obj_set_style_text_letter_space(ui_active1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_active1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_active1, &ui_font_micro8b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_inactiveDot3 = lv_arc_create(ui_cntFooter1);
lv_obj_set_width( ui_inactiveDot3, 8);
lv_obj_set_height( ui_inactiveDot3, 8);
lv_obj_set_x( ui_inactiveDot3, 110 );
lv_obj_set_y( ui_inactiveDot3, 0 );
lv_obj_set_align( ui_inactiveDot3, LV_ALIGN_LEFT_MID );
lv_arc_set_value(ui_inactiveDot3, 100);
lv_arc_set_bg_angles(ui_inactiveDot3,0,360);

ui_object_set_themeable_style_property(ui_inactiveDot3, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_textTertiary);
ui_object_set_themeable_style_property(ui_inactiveDot3, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_textTertiary);

lv_obj_set_style_pad_left(ui_inactiveDot3, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_inactiveDot3, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_inactiveDot3, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_inactiveDot3, -40, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_inactiveDot4 = lv_arc_create(ui_cntFooter1);
lv_obj_set_width( ui_inactiveDot4, 8);
lv_obj_set_height( ui_inactiveDot4, 8);
lv_obj_set_x( ui_inactiveDot4, 190 );
lv_obj_set_y( ui_inactiveDot4, 0 );
lv_obj_set_align( ui_inactiveDot4, LV_ALIGN_LEFT_MID );
lv_arc_set_value(ui_inactiveDot4, 100);
lv_arc_set_bg_angles(ui_inactiveDot4,0,360);

ui_object_set_themeable_style_property(ui_inactiveDot4, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_textTertiary);
ui_object_set_themeable_style_property(ui_inactiveDot4, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_textTertiary);

lv_obj_set_style_pad_left(ui_inactiveDot4, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_inactiveDot4, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_inactiveDot4, -40, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_inactiveDot4, -40, LV_PART_KNOB| LV_STATE_DEFAULT);

}

void ui_scrClimate_screen_destroy(void)
{
   if (ui_scrClimate) lv_obj_del(ui_scrClimate);

// NULL screen variables
ui_scrClimate= NULL;
ui_topBar1= NULL;
ui_cntTemperature= NULL;
ui_tempArc= NULL;
ui_tempValue= NULL;
ui_tempUnit= NULL;
ui_tempLabel= NULL;
ui_tempMinMax= NULL;
ui_cntHumidity= NULL;
ui_humArc= NULL;
ui_humValue= NULL;
ui_humUnit= NULL;
ui_humLabel= NULL;
ui_humMinMax= NULL;
ui_cntFooter1= NULL;
ui_cntActiveStatus1= NULL;
ui_iconLeft1= NULL;
ui_iconRight1= NULL;
ui_activeDot1= NULL;
ui_active1= NULL;
ui_inactiveDot3= NULL;
ui_inactiveDot4= NULL;

}
