// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCRMOTION_H
#define UI_SCRMOTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMotion
extern void ui_scrMotion_screen_init(void);
extern void ui_scrMotion_screen_destroy(void);
extern lv_obj_t *ui_scrMotion;
extern lv_obj_t *ui_topBar2;
extern lv_obj_t *ui_ring;
extern lv_obj_t *ui_lvl;
extern lv_obj_t *ui_cntFooter2;
extern lv_obj_t *ui_cntActiveStatus2;
extern lv_obj_t *ui_iconLeft2;
extern lv_obj_t *ui_iconRight2;
extern lv_obj_t *ui_activeDot2;
extern lv_obj_t *ui_active2;
extern lv_obj_t *ui_inactiveDot5;
extern lv_obj_t *ui_inactiveDot6;
extern lv_obj_t *ui_hline;
extern lv_obj_t *ui_cntAxisX;
extern lv_obj_t *ui_axisX;
extern lv_obj_t *ui_axisXv;
extern lv_obj_t *ui_unit1;
extern lv_obj_t *ui_cntAxisY;
extern lv_obj_t *ui_axisY;
extern lv_obj_t *ui_axisYv;
extern lv_obj_t *ui_unit2;
extern lv_obj_t *ui_cntAxisZ;
extern lv_obj_t *ui_axisZ;
extern lv_obj_t *ui_axisZv;
extern lv_obj_t *ui_unit3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

