// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCRBLE_H
#define UI_SCRBLE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrBLE
extern void ui_scrBLE_screen_init(void);
extern void ui_scrBLE_screen_destroy(void);
extern lv_obj_t *ui_scrBLE;
extern lv_obj_t *ui_topBar;
extern lv_obj_t *ui_cntHero;
extern lv_obj_t *ui_statusRing;
extern lv_obj_t *ui_statusInsideRing;
extern lv_obj_t *ui_lblState;
extern lv_obj_t *ui_lblSubHero;
extern lv_obj_t *ui_cntNotifyList;
extern lv_obj_t *ui_lblNotifyList;
extern lv_obj_t *ui_notifyCount;
extern lv_obj_t *ui_cntNotifyItem1;
extern lv_obj_t *ui_notifyItem1Name;
extern lv_obj_t *ui_notifyItem1UUID;
extern lv_obj_t *ui_notifyItem1Switch;
extern lv_obj_t *ui_notifyItem1SwitchLbl;
extern lv_obj_t *ui_cntNotifyItem2;
extern lv_obj_t *ui_notifyItem2Name;
extern lv_obj_t *ui_notifyItem2UUID;
extern lv_obj_t *ui_notifyItem2Switch;
extern lv_obj_t *ui_notifyItem2SwitchLbl;
extern lv_obj_t *ui_cntNotifyItem3;
extern lv_obj_t *ui_notifyItem3Name;
extern lv_obj_t *ui_notifyItem3UUID;
extern lv_obj_t *ui_notifyItem3Switch;
extern lv_obj_t *ui_notifyItem3SwitchLbl;
extern lv_obj_t *ui_cntNotifyItem4;
extern lv_obj_t *ui_notifyItem4Name;
extern lv_obj_t *ui_notifyItem4UUID;
extern lv_obj_t *ui_notifyItem4Switch;
extern lv_obj_t *ui_notifyItem4SwitchLbl;
extern lv_obj_t *ui_cntNotifyItem5;
extern lv_obj_t *ui_notifyItem5Name;
extern lv_obj_t *ui_notifyItem5UUID;
extern lv_obj_t *ui_notifyItem5Switch;
extern lv_obj_t *ui_notifyItem5SwitchLbl;
extern lv_obj_t *ui_cntFooter;
extern lv_obj_t *ui_cntActiveStatus;
extern lv_obj_t *ui_iconLeft;
extern lv_obj_t *ui_iconRight;
extern lv_obj_t *ui_activeDot;
extern lv_obj_t *ui_active;
extern lv_obj_t *ui_inactiveDot1;
extern lv_obj_t *ui_inactiveDot2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

