// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT topBar

lv_obj_t *ui_topBar_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_topBar;
cui_topBar = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_topBar);
lv_obj_set_width( cui_topBar, 320);
lv_obj_set_height( cui_topBar, 28);
lv_obj_remove_flag( cui_topBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(cui_topBar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(cui_topBar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(cui_topBar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_topBar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_dot;
cui_dot = lv_obj_create(cui_topBar);
lv_obj_set_width( cui_dot, 9);
lv_obj_set_height( cui_dot, 9);
lv_obj_set_x( cui_dot, 12 );
lv_obj_set_y( cui_dot, 0 );
lv_obj_set_align( cui_dot, LV_ALIGN_LEFT_MID );
lv_obj_remove_flag( cui_dot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_dot, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_dot, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_statusConnected);
ui_object_set_themeable_style_property(cui_dot, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_statusConnected);
ui_object_set_themeable_style_property(cui_dot, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_statusConnected);
ui_object_set_themeable_style_property(cui_dot, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_statusConnected);
lv_obj_set_style_border_width(cui_dot, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_bleStatus;
cui_bleStatus = lv_label_create(cui_topBar);
lv_obj_set_width( cui_bleStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_bleStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_bleStatus, 28 );
lv_obj_set_y( cui_bleStatus, 0 );
lv_obj_set_align( cui_bleStatus, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_bleStatus,"BLE");
lv_obj_set_style_text_font(cui_bleStatus, &ui_font_caps11b, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_deviceName;
cui_deviceName = lv_label_create(cui_topBar);
lv_obj_set_width( cui_deviceName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_deviceName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_deviceName, 208 );
lv_obj_set_y( cui_deviceName, 0 );
lv_obj_set_align( cui_deviceName, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_deviceName,"SensorNode-01");
lv_obj_set_style_text_font(cui_deviceName, &ui_font_sub10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_iconSignal;
cui_iconSignal = lv_image_create(cui_topBar);
lv_image_set_src(cui_iconSignal, &ui_img_icons_signal_png);
lv_obj_set_width( cui_iconSignal, 18);
lv_obj_set_height( cui_iconSignal, 18);
lv_obj_set_x( cui_iconSignal, 290 );
lv_obj_set_y( cui_iconSignal, 0 );
lv_obj_set_align( cui_iconSignal, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( cui_iconSignal, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( cui_iconSignal, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(cui_iconSignal,153);
ui_object_set_themeable_style_property(cui_iconSignal, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_statusConnected);
ui_object_set_themeable_style_property(cui_iconSignal, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_statusConnected);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_TOPBAR_NUM);
children[UI_COMP_TOPBAR_TOPBAR] = cui_topBar;
children[UI_COMP_TOPBAR_DOT] = cui_dot;
children[UI_COMP_TOPBAR_BLESTATUS] = cui_bleStatus;
children[UI_COMP_TOPBAR_DEVICENAME] = cui_deviceName;
children[UI_COMP_TOPBAR_ICONSIGNAL] = cui_iconSignal;
lv_obj_add_event_cb(cui_topBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_topBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_topBar_create_hook(cui_topBar);
return cui_topBar; 
}

