// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_COMP_TOPBAR_H
#define _UI_COMP_TOPBAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT topBar
#define UI_COMP_TOPBAR_TOPBAR 0
#define UI_COMP_TOPBAR_DOT 1
#define UI_COMP_TOPBAR_BLESTATUS 2
#define UI_COMP_TOPBAR_DEVICENAME 3
#define UI_COMP_TOPBAR_ICONSIGNAL 4
#define _UI_COMP_TOPBAR_NUM 5
lv_obj_t *ui_topBar_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
