// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_scrBLE.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_bg_main_png);   // assets/bg_main.png
LV_IMG_DECLARE( ui_img_icon_temperature_png);   // assets/icon_temperature.png
LV_IMG_DECLARE( ui_img_icon_humidity_png);   // assets/icon_humidity.png

// FONTS
LV_FONT_DECLARE( ui_font_Nunito28);
LV_FONT_DECLARE( ui_font_Nunito20);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
