// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_scrBLE.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_icons_signal_png);   // assets/icons/signal.png
LV_IMG_DECLARE( ui_img_icons_left_png);   // assets/icons/left.png
LV_IMG_DECLARE( ui_img_icons_right_png);   // assets/icons/right.png

// FONTS
LV_FONT_DECLARE( ui_font_caps11b);
LV_FONT_DECLARE( ui_font_micro8b);
LV_FONT_DECLARE( ui_font_mono17m);
LV_FONT_DECLARE( ui_font_mono9);
LV_FONT_DECLARE( ui_font_sub10);
LV_FONT_DECLARE( ui_font_title17xb);
LV_FONT_DECLARE( ui_font_value22b);
LV_FONT_DECLARE( ui_font_body12sb);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
