// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_backGround[3] = {0x0A0E13, 0x0A0E13, 0xECEFF2};
const ui_theme_variable_t _ui_theme_alpha_backGround[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_textPrimary[3] = {0xE8EEF4, 0xE8EEF4, 0x15202B};
const ui_theme_variable_t _ui_theme_alpha_textPrimary[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_textSecondary[3] = {0x8595A3, 0x8595A3, 0x5D6B78};
const ui_theme_variable_t _ui_theme_alpha_textSecondary[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_textTertiary[3] = {0x566472, 0x566472, 0x9AA6B1};
const ui_theme_variable_t _ui_theme_alpha_textTertiary[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_accent[3] = {0x2DD4BF, 0x2DD4BF, 0x0E9B8D};
const ui_theme_variable_t _ui_theme_alpha_accent[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_accentBorder[3] = {0x0D3A36, 0x0D3A36, 0xCFEEE9};
const ui_theme_variable_t _ui_theme_alpha_accentBorder[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_gauge[3] = {0x1D2832, 0x1D2832, 0xE2E7EB};
const ui_theme_variable_t _ui_theme_alpha_gauge[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_border[3] = {0x23303D, 0x23303D, 0xD8DEE4};
const ui_theme_variable_t _ui_theme_alpha_border[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_divider[3] = {0x1A232E, 0x1A232E, 0xE6EAEE};
const ui_theme_variable_t _ui_theme_alpha_divider[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_statusConnected[3] = {0x34D399, 0x34D399, 0x0E9B8D};
const ui_theme_variable_t _ui_theme_alpha_statusConnected[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_statusAdvertisin[3] = {0xFBBF24, 0xFBBF24, 0xC97A08};
const ui_theme_variable_t _ui_theme_alpha_statusAdvertisin[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_statusDisconn[3] = {0xF87171, 0xF87171, 0xDC4040};
const ui_theme_variable_t _ui_theme_alpha_statusDisconn[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_DARK;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

