// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BACKGROUND 0
#define UI_THEME_COLOR_TEXTPRIMARY 1
#define UI_THEME_COLOR_TEXTSECONDARY 2
#define UI_THEME_COLOR_TEXTTERTIARY 3
#define UI_THEME_COLOR_ACCENT 4
#define UI_THEME_COLOR_ACCENTBORDER 5
#define UI_THEME_COLOR_GAUGE 6
#define UI_THEME_COLOR_BORDER 7
#define UI_THEME_COLOR_DIVIDER 8
#define UI_THEME_COLOR_STATUSCONNECTED 9
#define UI_THEME_COLOR_STATUSADVERTISIN 10
#define UI_THEME_COLOR_STATUSDISCONN 11

#define UI_THEME_DEFAULT 0

#define UI_THEME_DARK 1

#define UI_THEME_LIGHT 2

extern const ui_theme_variable_t _ui_theme_color_backGround[3];
extern const ui_theme_variable_t _ui_theme_alpha_backGround[3];

extern const ui_theme_variable_t _ui_theme_color_textPrimary[3];
extern const ui_theme_variable_t _ui_theme_alpha_textPrimary[3];

extern const ui_theme_variable_t _ui_theme_color_textSecondary[3];
extern const ui_theme_variable_t _ui_theme_alpha_textSecondary[3];

extern const ui_theme_variable_t _ui_theme_color_textTertiary[3];
extern const ui_theme_variable_t _ui_theme_alpha_textTertiary[3];

extern const ui_theme_variable_t _ui_theme_color_accent[3];
extern const ui_theme_variable_t _ui_theme_alpha_accent[3];

extern const ui_theme_variable_t _ui_theme_color_accentBorder[3];
extern const ui_theme_variable_t _ui_theme_alpha_accentBorder[3];

extern const ui_theme_variable_t _ui_theme_color_gauge[3];
extern const ui_theme_variable_t _ui_theme_alpha_gauge[3];

extern const ui_theme_variable_t _ui_theme_color_border[3];
extern const ui_theme_variable_t _ui_theme_alpha_border[3];

extern const ui_theme_variable_t _ui_theme_color_divider[3];
extern const ui_theme_variable_t _ui_theme_alpha_divider[3];

extern const ui_theme_variable_t _ui_theme_color_statusConnected[3];
extern const ui_theme_variable_t _ui_theme_alpha_statusConnected[3];

extern const ui_theme_variable_t _ui_theme_color_statusAdvertisin[3];
extern const ui_theme_variable_t _ui_theme_alpha_statusAdvertisin[3];

extern const ui_theme_variable_t _ui_theme_color_statusDisconn[3];
extern const ui_theme_variable_t _ui_theme_alpha_statusDisconn[3];

extern const uint32_t* ui_theme_colors[3];
extern const uint8_t* ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
